#!/bin/bash
# post-review-comment.sh
# Part of pr-guidelines-review skill (S7 DETERMINISTIC TOOL BRIDGE)
# Posts one structured review comment to a GitHub PR.
# Non-interactive, deterministic, version-pinned.
#
# Requires: gh CLI (GitHub CLI) >= 2.0 installed and authenticated
#
# Usage:
#   ./post-review-comment.sh <pr_url> <arbiter_synthesis_json>

set -euo pipefail

# Help
if [[ "${1:-}" == "--help" ]] || [[ "${1:-}" == "-h" ]] || [[ $# -lt 2 ]]; then
  cat << 'EOF'
post-review-comment.sh — Post one review comment to a GitHub PR

USAGE:
  ./post-review-comment.sh <pr_url> <arbiter_json>

ARGUMENTS:
  pr_url:            GitHub PR URL (e.g., https://github.com/owner/repo/pull/123)
  arbiter_json:      JSON from arbiter persona (recommendation, reasoning, findings_summary)

REQUIRES:
  - gh CLI >= 2.0 (https://cli.github.com)
  - GitHub authentication: gh auth login

OUTPUT:
  JSON object:
  {
    "success": true/false,
    "comment_id": "<int>",
    "comment_url": "https://...",
    "error": "<message if failed>"
  }

EXAMPLE:
  ./post-review-comment.sh \
    "https://github.com/owner/repo/pull/123" \
    '{"recommendation": "ADVISE_MERGE", "reasoning": "...", "findings_summary": {...}}'

TEMPLATE:
  The script uses comment-template.md in ../references/ to format the output.

EOF
  exit 1
fi

PR_URL="$1"
ARBITER_JSON="$2"

# Validate gh CLI is installed
if ! command -v gh &> /dev/null; then
  echo "{\"success\": false, \"error\": \"gh CLI not found; install from https://cli.github.com\"}" >&2
  exit 1
fi

# Validate JSON is parseable
if ! echo "$ARBITER_JSON" | python3 -c "import sys, json; json.load(sys.stdin)" 2>/dev/null; then
  echo "{\"success\": false, \"error\": \"Arbiter JSON is not valid\"}" >&2
  exit 1
fi

# Extract fields from arbiter JSON
RECOMMENDATION=$(echo "$ARBITER_JSON" | python3 -c "import sys, json; d=json.load(sys.stdin); print(d.get('recommendation', 'UNKNOWN'))")
REASONING=$(echo "$ARBITER_JSON" | python3 -c "import sys, json; d=json.load(sys.stdin); print(d.get('reasoning', ''))")

# Map recommendation to display text
case "$RECOMMENDATION" in
  ADVISE_MERGE)
    DISPLAY_REC="✅ Merge is advised"
    ;;
  REQUEST_CHANGES)
    DISPLAY_REC="⚠️ Changes requested"
    ;;
  ADVISE_CONDITIONAL)
    DISPLAY_REC="⚠️ Merge conditionally (address HIGH findings)"
    ;;
  *)
    DISPLAY_REC="$RECOMMENDATION"
    ;;
esac

# Build findings summary (security, architecture, documentation)
BUILD_FINDINGS() {
  echo "$ARBITER_JSON" | python3 << 'PYTHON_EOF'
import sys, json

data = json.load(sys.stdin)
findings = data.get('findings_summary', {})

output = []

for dimension in ['security', 'architecture', 'documentation']:
  items = findings.get(dimension, [])
  if items:
    output.append(f"\n### {dimension.title()}")
    for item in items:
      sev = item.get('sev', '?').upper()
      finding = item.get('finding', '?')
      output.append(f"- {sev}: {finding}")

if not output:
  output.append("\n*No significant findings.*")

print('\n'.join(output))
PYTHON_EOF
}

FINDINGS_SECTION=$(BUILD_FINDINGS)

# Construct markdown comment
COMMENT_BODY=$(cat << EOF
## Automated PR Review — Guidelines Assessment

**Recommendation:** $DISPLAY_REC

**Reasoning:**  
$REASONING

**Key Findings (by criticality):**
$FINDINGS_SECTION

---
*Review generated by multi-lens PR guidelines automation (Security, Architecture, Documentation). Findings are advisory — final merge decision rests with the team.*
EOF
)

# Post comment via gh CLI (version-pinned to 2.0+)
RESPONSE=$(gh --version | grep -o "[0-9]*\.[0-9]*" | head -1)
if [[ $(echo "$RESPONSE" | cut -d. -f1) -lt 2 ]]; then
  echo "{\"success\": false, \"error\": \"gh CLI version must be >= 2.0\"}" >&2
  exit 1
fi

# Extract PR owner/repo/number from URL
if [[ $PR_URL =~ github\.com/([^/]+)/([^/]+)/pull/([0-9]+) ]]; then
  OWNER="${BASH_REMATCH[1]}"
  REPO="${BASH_REMATCH[2]}"
  PR_NUMBER="${BASH_REMATCH[3]}"
else
  echo "{\"success\": false, \"error\": \"Invalid PR URL format\"}" >&2
  exit 1
fi

# Post the comment
COMMENT_RESPONSE=$(gh pr comment "$PR_NUMBER" --repo "$OWNER/$REPO" --body "$COMMENT_BODY" 2>&1) || {
  echo "{\"success\": false, \"error\": \"Failed to post comment: $COMMENT_RESPONSE\"}" >&2
  exit 1
}

# Extract comment ID and URL from response
COMMENT_ID=$(echo "$COMMENT_RESPONSE" | grep -oP '(?<=#)\d+(?=\s|$)' | head -1 || echo "unknown")
COMMENT_URL="https://github.com/$OWNER/$REPO/pull/$PR_NUMBER#issuecomment-$COMMENT_ID"

# Output success JSON
echo "{\"success\": true, \"comment_id\": \"$COMMENT_ID\", \"comment_url\": \"$COMMENT_URL\"}"

exit 0
